New Module: Using Enclaves with Amazon EKS
aws-samples/amazon-eks-security-immersion-day pull request #27
Opened 2024-07-19 14:35 UTC by berry2012

*Issue #23 

*Description of changes:*
Initial content - New Module: Using Enclaves with Amazon EKS

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-09 14:50 UTC, vpodugu commented on content/8-infrastructure-security/2-using-enclaves/2-create-node/index.en.md
> +readonly CPU_COUNT=4
Ask user to enter the value.

2024-08-09 14:50 UTC, vpodugu commented on content/8-infrastructure-security/2-using-enclaves/2-create-node/index.en.md
> +readonly MEMORY_MIB=768
Ask user to enter the value.

2024-08-09 14:52 UTC, vpodugu commented on content/8-infrastructure-security/2-using-enclaves/index.en.md
> +[AWS Nitro Enclaves](https://aws.amazon.com/ec2/nitro/nitro-enclaves/) is an [Amazon EC2](https://aws-content-sandbox.aka.amazon.com/ec2/) capability that enables customers to create isolated compute
Remove the link for Amazon EC2 
Remove the link for Amazon EKS

2024-08-09 14:53 UTC, vpodugu commented on content/8-infrastructure-security/2-using-enclaves/index.en.md
> +
Add a visual representation.

2024-08-09 14:55 UTC, vpodugu requested changes
Please fix these.

2024-09-10 12:47 UTC, allamand approved these changes
As discuss let's merge it

2024-09-10 12:47 UTC, merged