Removed Cloud9 in Fully Private EKS Cluster with VPC peering
aws-samples/amazon-eks-security-immersion-day pull request #36
Opened 2024-10-09 20:58 UTC by berry2012

*Issue #35 *

*Description of changes: Removed cloud9 from fully private eks cluster module. Uses vpc peering*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2025-01-25 14:53 UTC, allamand requested changes

2025-01-25 14:53 UTC, allamand commented on content/6-network-security/4-fully-private-cluster/1-create-cluster/index.en.md
> +"https://AFB4045AF25413FF766AD8CA1FF0CAEA.yl4.us-west-2.eks.amazonaws.com"
Which command give this output ?

2025-01-25 14:53 UTC, allamand commented on content/6-network-security/4-fully-private-cluster/1-create-cluster/index.en.md
> +::::expand{header="Check Output"}
This is example output, it miss the command to run to have it ?

2025-01-25 14:53 UTC, allamand commented on content/6-network-security/4-fully-private-cluster/2-install-alb-controller-addon/index.en.md
> +Download an IAM policy for the AWS Load Balancer Controller that allows it to make calls to AWS APIs on your behalf from the Cloud9/Workshop IDE instance.
Remove cloud9

2025-01-25 14:53 UTC, allamand commented on content/6-network-security/4-fully-private-cluster/1-create-cluster/index.en.md
> +```bash
Remove bash we don’t want user to copy this example output

2025-03-24 18:27 UTC, berry2012 commented on content/6-network-security/4-fully-private-cluster/1-create-cluster/index.en.md
> +"https://AFB4045AF25413FF766AD8CA1FF0CAEA.yl4.us-west-2.eks.amazonaws.com"
added

2025-03-24 18:28 UTC, berry2012 commented on content/6-network-security/4-fully-private-cluster/1-create-cluster/index.en.md
> +::::expand{header="Check Output"}
added

2025-03-24 18:28 UTC, berry2012 commented on content/6-network-security/4-fully-private-cluster/2-install-alb-controller-addon/index.en.md
> +Download an IAM policy for the AWS Load Balancer Controller that allows it to make calls to AWS APIs on your behalf from the Cloud9/Workshop IDE instance.
done

2025-03-24 18:29 UTC, berry2012 commented on content/6-network-security/4-fully-private-cluster/1-create-cluster/index.en.md
> +```bash
done

2025-03-28 18:17 UTC, merged

2025-03-28 18:17 UTC, allamand commented
Thanks :)